version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5010:5010" # Map container port 8080 to host port 8080
    volumes:
      - .:/app # Mount the project directory for live updates
      - /app/node_modules # Prevent re-installing node_modules on every run
    command: npm run dev # Run the Vue dev server
    environment:
      - NODE_ENV=development
    networks:
      backend:
        ipv4_address: 10.10.1.20
        aliases:
          - app


networks:
  backend:
    name: FinScraping
    external: true